name: CI/CD to ECR and EC2

on:
  push:
    branches: [ "action" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run Unit Tests
      run: |
        pip install -r requirements.txt
        export PYTHONPATH=$PYTHONPATH:$(pwd)/src
        python -m unittest discover -s tests -p "test_*.py"

    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v2
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ${{ secrets.AWS_REGION }}

    # - name: Login to Amazon ECR
    #   id: login-ecr
    #   uses: aws-actions/amazon-ecr-login@v2

    # - name: Build, Tag and Push Docker Image to ECR
    #   env:
    #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    #     IMAGE_TAG: rania30111
    #   run: |
    #     docker build -t churn-prediction:$IMAGE_TAG .
    #     docker tag churn-prediction:$IMAGE_TAG $ECR_REGISTRY/churn-prediction:$IMAGE_TAG
    #     docker push $ECR_REGISTRY/churn-prediction:$IMAGE_TAG

    # - name: Deploy to EC2
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.EC2_HOST }}
    #     username: ${{ secrets.EC2_USERNAME }}
    #     key: ${{ secrets.EC2_SSH_KEY }}
    #     script: |
    #       aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
    #       docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/churn-prediction:rania30111
    #       docker stop churn-prediction || true
    #       docker rm churn-prediction || true
    #       docker run -d -p 443:8005 --name churn-prediction ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/churn-prediction:rania30111
